### ISSUE TITLE
Error on make

### ISSUE THREAD

**Issue by artemyerofieievsc** [woboq/moc-ng#10]
When run make get this error:
> src/CMakeFiles/moc.dir/build.make:301: *** target pattern contains no `%'.  Stop.

The line is:
`301: src/libmocng_plugin.1.0.dylib: /bin/sh:`

clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin/.

Is it because this version of llvm|clang is not supported yet?  How can this be fixed?

**Comment by ogoffart** [comment]
Clang 4 is well supported.
If anything, this might be a problem specific on mac. But i cannot really say what the problem is.

**Comment by ogoffart** [comment]
Closing old issue.
