### ISSUE TITLE
make: *** No rule to make target 'install'.  Stop.

### ISSUE THREAD

**Issue by Petross404** [woboq/moc-ng#11]
An ebuild I wrote to install moc-ng in my systems, after succesfully compiling moc-ng, stops when it tries to find "install" target.

I think it is missing from the Makefile.

**Comment by ogoffart** [comment]
Right, there are currently no installation rules.

**Comment by Petross404** [comment]
> Right, there are currently no installation rules.

So how can I install it except manually copying them?

**Comment by Petross404** [comment]
Nice, thanks!
