### ISSUE TITLE
Support for Qt 4 (4.8)

### ISSUE THREAD

**Issue by nanoant** [woboq/moc-ng#5]
**This plugin is simply awesome!** It would be even greater if it could also replace Qt 4.8 moc.

Since Qt 5 is really major change which relies on OpenGL comparing to Qt 4.8. Many apps & developers tend to stay with Qt 4.x.

It is there any reason **moc-ng** couldn't work for Qt 4.x?

**Comment by ogoffart** [comment]
Qt4 is no longer supported for a long time.
